"""pack image update

Revision ID: 02b7631ecec1
Revises: 09b024f52da7
Create Date: 2021-03-15 20:32:02.760865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b7631ecec1'
down_revision = '09b024f52da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packimage', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packimage', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
