"""pack_image url remove

Revision ID: 09b024f52da7
Revises: 96b0490a76db
Create Date: 2021-03-13 15:58:27.113161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b024f52da7'
down_revision = '96b0490a76db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'image_url')
    op.alter_column('packimage', 'pack_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packimage', 'pack_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('pack', sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
