"""item_pk

Revision ID: 14e4e58daf3d
Revises: 59cf5f2cbbb7
Create Date: 2022-04-02 14:24:48.209071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e4e58daf3d'
down_revision = '59cf5f2cbbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
