"""add created_at field to image

Revision ID: 15b19b35fd95
Revises: 52e5bf78a86c
Create Date: 2021-10-29 22:29:39.890415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b19b35fd95'
down_revision = '52e5bf78a86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('created_at', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    ## op.drop_column('image', 'created_at')
    # ### end Alembic commands ###
