"""pack image url

Revision ID: 15f992354be3
Revises: e2b94032ba12
Create Date: 2021-03-15 21:16:00.454849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f992354be3'
down_revision = 'e2b94032ba12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
