"""price,weight nullable

Revision ID: 208d3d3b20da
Revises: 96546aed4504
Create Date: 2022-03-26 13:59:18.306959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208d3d3b20da'
down_revision = '96546aed4504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
