"""init

Revision ID: 23219237d47f
Revises: 
Create Date: 2021-02-14 21:51:34.229739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23219237d47f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
