"""pack -> trip

Revision ID: 27b7c0329687
Revises: a27715e34e40
Create Date: 2022-03-17 17:16:36.729982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27b7c0329687'
down_revision = 'a27715e34e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('pack', 'trip')
    # op.execute('ALTER SEQUENCE  packcondition_pack_id_fkey RENAME TO tripcondition_trip_id_fkey')
    op.execute('ALTER SEQUENCE  image_pack_id_fkey RENAME TO image_trip_id_fkey')
    op.execute('ALTER SEQUENCE  likepack_pack_id_fkey RENAME TO likepack_trip_id_fkey')
    op.execute('ALTER SEQUENCE  reported_pack_id_fkey RENAME TO reported_trip_id_fkey')
    op.execute('ALTER SEQUENCE  comment_pack_id_fkey RENAME TO comment_trip_id_fkey')
    op.execute('ALTER INDEX pack_pkey RENAME TO trip_pkey')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('trip', 'pack')
    # op.execute('ALTER SEQUENCE  packcondition_trip_id_fkey RENAME TO packcondition_pack_id_fkey')
    op.execute('ALTER SEQUENCE  image_trip_id_fkey RENAME TO image_pack_id_fkey')
    op.execute('ALTER SEQUENCE  likepack_trip_id_fkey RENAME TO likepack_pack_id_fkey')
    op.execute('ALTER SEQUENCE  reported_trip_id_fkey RENAME TO reported_pack_id_fkey')
    op.execute('ALTER SEQUENCE  comment_trip_id_fkey RENAME TO comment_pack_id_fkey')
    op.execute('ALTER INDEX trip_pkey RENAME TO pack_pkey')

    # ### end Alembic commands ###
