"""remove consumable category

Revision ID: 2d1fdea66e28
Revises: f4e421fac3e7
Create Date: 2022-04-20 16:00:43.373260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1fdea66e28'
down_revision = 'f4e421fac3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemcategory', 'consumable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemcategory', sa.Column('consumable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
