"""sort_order

Revision ID: 351f952da2b1
Revises: 208d3d3b20da
Create Date: 2022-04-02 13:37:29.986982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351f952da2b1'
down_revision = '208d3d3b20da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.alter_column('category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('item', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'sort_order')
    op.alter_column('category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('category', 'sort_order')
    # ### end Alembic commands ###
