"""general image table

Revision ID: 3a9b84fb3302
Revises: 44c5d9000c6b
Create Date: 2021-03-18 15:00:35.443407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9b84fb3302'
down_revision = '44c5d9000c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_packimage_id', table_name='packimage')
    op.drop_table('packimage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packimage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('s3_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], name='packimage_pack_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='packimage_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='packimage_pkey')
    )
    op.create_index('ix_packimage_id', 'packimage', ['id'], unique=False)
    # ### end Alembic commands ###
