"""caegory

Revision ID: 3cbfae9d3e32
Revises: 835faa34f4d2
Create Date: 2022-04-02 14:41:56.223454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbfae9d3e32'
down_revision = '835faa34f4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('consumable', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'category_id')
    op.drop_column('category', 'sort_order')
    op.drop_column('category', 'consumable')
    # ### end Alembic commands ###
