"""category_update

Revision ID: 59cf5f2cbbb7
Revises: f00b6e1f56cf
Create Date: 2022-04-02 14:19:40.628085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cf5f2cbbb7'
down_revision = 'f00b6e1f56cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_name_key', 'category', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('category_name_key', 'category', ['name'])
    # ### end Alembic commands ###
