"""cta.id

Revision ID: 61b4e576cfef
Revises: dc9232b5a547
Create Date: 2022-04-02 14:34:37.238336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b4e576cfef'
down_revision = 'dc9232b5a547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'usercategory', ['category_id'], ['id'])
    op.alter_column('usercategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercategory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usercategory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'category_id')
    # ### end Alembic commands ###
