"""s3_key_thumb

Revision ID: 6654aae30a12
Revises: 1149ff60d9c5
Create Date: 2021-11-17 21:11:28.146117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6654aae30a12'
down_revision = '1149ff60d9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('s3_key_thumb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 's3_key_thumb')
    # ### end Alembic commands ###
