"""add removed column to brand, product

Revision ID: 6b5b5971cda2
Revises: e8752b671fa6
Create Date: 2021-03-09 21:27:18.488955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5b5971cda2'
down_revision = 'e8752b671fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('removed', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('removed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'removed')
    op.drop_column('brand', 'removed')
    # ### end Alembic commands ###
