"""remove planning field

Revision ID: 728a0cd593c6
Revises: 23219237d47f
Create Date: 2021-10-22 22:31:05.010424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728a0cd593c6'
down_revision = '23219237d47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'planning')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('planning', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
