"""img collection

Revision ID: 72bc79ba226a
Revises: a433ba8fd927
Create Date: 2021-11-26 13:12:21.142186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bc79ba226a'
down_revision = 'a433ba8fd927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
