"""currency enum lib

Revision ID: 72c90e10b5c2
Revises: 3a9b84fb3302
Create Date: 2021-03-20 22:33:42.664326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c90e10b5c2'
down_revision = '3a9b84fb3302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
