"""avatar-image relationship

Revision ID: 7fb4b3d6b60b
Revises: adf822bbc456
Create Date: 2021-09-22 20:51:31.027254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb4b3d6b60b'
down_revision = 'adf822bbc456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('avatar', sa.Boolean(), nullable=True))
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('image', 'avatar')
    # ### end Alembic commands ###
