"""cat.id

Revision ID: 835faa34f4d2
Revises: 61b4e576cfef
Create Date: 2022-04-02 14:35:21.838773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835faa34f4d2'
down_revision = '61b4e576cfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usercategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercategory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usercategory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
