"""remove item defaults

Revision ID: 96546aed4504
Revises: b87eff5a0115
Create Date: 2022-03-26 13:57:41.068183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96546aed4504'
down_revision = 'b87eff5a0115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
