"""pack image table

Revision ID: 96b0490a76db
Revises: 6b5b5971cda2
Create Date: 2021-03-13 15:41:38.732337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b0490a76db'
down_revision = '6b5b5971cda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
