"""add caption field

Revision ID: a27715e34e40
Revises: 57b0d7f1ecd4
Create Date: 2022-02-10 20:03:53.649315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27715e34e40'
down_revision = '57b0d7f1ecd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('caption', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'caption')
    # ### end Alembic commands ###
