"""image sort order

Revision ID: a433ba8fd927
Revises: 6654aae30a12
Create Date: 2021-11-26 12:37:22.292598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a433ba8fd927'
down_revision = '6654aae30a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'sort_order')
    # ### end Alembic commands ###
