"""trip rename

Revision ID: a6724469840f
Revises: 27b7c0329687
Create Date: 2022-03-17 20:23:14.268686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6724469840f'
down_revision = '27b7c0329687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('likepack', 'liketrip')
    op.rename_table('packcondition', 'tripcondition')
    op.rename_table('packgeography', 'tripgeography')

    op.alter_column('trip', 'trail_name', new_column_name='location')
    op.alter_column('trip', 'public', new_column_name='published')
    op.alter_column('trip', 'region', new_column_name='title')
    op.drop_column('trip', 'planning_notes')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO
    # ### end Alembic commands ###


