"""social profile urls

Revision ID: adf822bbc456
Revises: 72c90e10b5c2
Create Date: 2021-09-21 21:45:17.981401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf822bbc456'
down_revision = '72c90e10b5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook_url', sa.String(length=100), nullable=True))
    op.drop_column('user', 'reddit_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reddit_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'facebook_url')
    # ### end Alembic commands ###
