"""remove enum fields; add unit fields

Revision ID: b0915db946ab
Revises: 728a0cd593c6
Create Date: 2021-10-23 13:04:05.987274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0915db946ab'
down_revision = '728a0cd593c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'unit',
               existing_type=postgresql.ENUM('OUNCES', 'POUNDS', 'GRAMS', 'KILOGRAMS', name='weightunit'),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.add_column('user', sa.Column('unit_distance', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('unit_temperature', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('unit_weight', sa.String(length=10), nullable=True))
    op.drop_column('user', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unit', postgresql.ENUM('IMPERIAL', 'METRIC', name='unitsystem'), autoincrement=False, nullable=True))
    op.drop_column('user', 'unit_weight')
    op.drop_column('user', 'unit_temperature')
    op.drop_column('user', 'unit_distance')
    op.alter_column('item', 'unit',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('OUNCES', 'POUNDS', 'GRAMS', 'KILOGRAMS', name='weightunit'),
               existing_nullable=True)
    # ### end Alembic commands ###
