"""Add category table

Revision ID: b3ee99d6ed17
Revises: 23219237d47f
Create Date: 2021-02-20 12:57:56.484878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ee99d6ed17'
down_revision = '23219237d47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'category_id')
    # ### end Alembic commands ###
