"""add pack, packItem

Revision ID: b87eff5a0115
Revises: a6724469840f
Create Date: 2022-03-17 20:33:02.971596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87eff5a0115'
down_revision = 'a6724469840f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER INDEX pack_pkey RENAME TO trip_pkey')
    op.execute('ALTER INDEX ix_pack_id RENAME TO ix_trip_id')

    op.create_table('pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_pack_id'), 'pack', ['id'], unique=False)
    op.add_column('comment', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_pack_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'trip', ['trip_id'], ['id'])
    op.drop_column('comment', 'pack_id')
    op.add_column('image', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.drop_constraint('image_pack_id_fkey', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'trip', ['trip_id'], ['id'])
    op.drop_column('image', 'pack_id')
    op.add_column('liketrip', sa.Column('trip_id', sa.Integer(), nullable=False))
    op.drop_constraint('likepack_pack_id_fkey', 'liketrip', type_='foreignkey')
    op.create_foreign_key(None, 'liketrip', 'trip', ['trip_id'], ['id'])
    op.drop_column('liketrip', 'pack_id')
    op.drop_constraint('packitem_pack_id_fkey', 'packitem', type_='foreignkey')
    op.create_foreign_key(None, 'packitem', 'pack', ['pack_id'], ['id'])
    op.add_column('reported', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.drop_constraint('reported_pack_id_fkey', 'reported', type_='foreignkey')
    op.create_foreign_key(None, 'reported', 'trip', ['trip_id'], ['id'])
    op.drop_column('reported', 'pack_id')

    op.alter_column('tripcondition', 'pack_id', new_column_name='trip_id')
    op.alter_column('tripgeography', 'pack_id', new_column_name='trip_id')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO
    # ### end Alembic commands ###
