"""cat.id

Revision ID: b95ab70a57cf
Revises: ded4b9b2f5e3
Create Date: 2022-04-02 14:31:32.613481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95ab70a57cf'
down_revision = 'ded4b9b2f5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercategory', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_usercategory_id'), 'usercategory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usercategory_id'), table_name='usercategory')
    op.drop_column('usercategory', 'id')
    # ### end Alembic commands ###
