"""currency_code

Revision ID: d025f7db4698
Revises: 2d1fdea66e28
Create Date: 2022-05-20 16:21:19.676082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd025f7db4698'
down_revision = '2d1fdea66e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'currency')
    # ### end Alembic commands ###
