"""usercategory.id

Revision ID: ded4b9b2f5e3
Revises: 14e4e58daf3d
Create Date: 2022-04-02 14:29:04.298460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded4b9b2f5e3'
down_revision = '14e4e58daf3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'usercategory', ['category_id'], ['id'])
    op.add_column('usercategory', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_usercategory_id'), 'usercategory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usercategory_id'), table_name='usercategory')
    op.drop_column('usercategory', 'id')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'category_id')
    # ### end Alembic commands ###
