"""pack image update

Revision ID: e2b94032ba12
Revises: 02b7631ecec1
Create Date: 2021-03-15 21:00:18.896660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b94032ba12'
down_revision = '02b7631ecec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packimage', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packimage', 'url')
    # ### end Alembic commands ###
