"""category_sort

Revision ID: f00b6e1f56cf
Revises: 351f952da2b1
Create Date: 2022-04-02 13:55:47.500924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00b6e1f56cf'
down_revision = '351f952da2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercategory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('consumable', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('_user_category_uc', 'category', type_='unique')
    op.drop_column('category', 'consumable')
    op.drop_column('category', 'sort_order')
    op.drop_constraint('item_category_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_category_id_fkey', 'item', 'category', ['category_id'], ['id'])
    op.add_column('category', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('consumable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('_user_category_uc', 'category', ['user_id', 'name'])
    op.alter_column('category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('category', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_table('usercategory')
    # ### end Alembic commands ###
