"""pack_item_sort

Revision ID: f4e421fac3e7
Revises: 49a560ef582f
Create Date: 2022-04-11 15:51:32.547251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e421fac3e7'
down_revision = '49a560ef582f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packitem', sa.Column('sort_order', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packitem', 'sort_order')
    # ### end Alembic commands ###
