services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .local.env
    environment:
      DEVELOPMENT: 1
      POSTGRES_HOST: database
      REDIS_URL: redis://redis:6379/0
    ports:
      - 80:80
    networks:
      - packstack
    depends_on:
      - database
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info
    env_file: .local.env
    environment:
      POSTGRES_HOST: database
      REDIS_URL: redis://redis:6379/0
    networks:
      - packstack
    depends_on:
      - database
      - redis

  redis:
    image: redis:7-alpine
    networks:
      - packstack
    ports:
      - "6379:6379"

  database:
    restart: always
    image: postgres:14.5-alpine
    env_file: .local.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - packstack
    ports:
      - "5432:5432"

networks:
  packstack:

volumes:
  pgdata:
