import os

DEVELOPMENT = os.getenv('DEVELOPMENT', 0)

POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_DB = os.getenv('POSTGRES_DB')
POSTGRES_PORT = os.getenv('POSTGRES_PORT', '5432')
DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

APP_HOST = os.getenv('APP_HOST')
JWT_SECRET = os.getenv('JWT_SECRET')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM')
DO_REGION = os.getenv('DO_REGION')
DO_ACCESS_TOKEN = os.getenv('DO_ACCESS_TOKEN')
DO_SPACES_KEY = os.getenv('DO_SPACES_KEY')
DO_SPACES_SECRET_KEY = os.getenv('DO_SPACES_SECRET_KEY')
DO_BUCKET = os.getenv('DO_BUCKET')
DO_CDN = os.getenv('DO_CDN')

RESEND_API_KEY = os.getenv('RESEND_API_KEY')
RESEND_AUDIENCE_ID = os.getenv('RESEND_AUDIENCE_ID')

GOOGLE_CLIENT_IDS = [
    cid.strip() for cid in os.getenv('GOOGLE_CLIENT_IDS', '').split(',') if cid.strip()
]
