version: '3.7'

services:
  postgres:
    restart: always
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: packstack
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - packstack

networks:
  packstack:

volumes:
  pgdata:
