apiVersion: v1
kind: Secret
metadata:
  name: do-postgres-secret
type: Opaque
data:
  postgres-username: ZG9hZG1pbg==
  postgres-password: ZGI4aGIyNGI4YzA1MmJoaQ==
  postgres-host: cHJpdmF0ZS1wYWNrc3RhY2stZGItc3RhZ2luZy1kby11c2VyLTg5NzY2NDItMC5iLmRiLm9uZGlnaXRhbG9jZWFuLmNvbQ==
  postgres-db: ZGVmYXVsdGRi